spring.application.name=kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.ack-mode=MANUAL
spring.kafka.consumer.enable-auto-commit=false
server.port=2226
logging.level.org.apache.kafka.clients.consumer.internals.AbstractCoordinator=DEBUG
logging.level.org.apache.kafka.clients.consumer.internals.ConsumerCoordinator=TRACE



